import type { AuditResult, Finding, CategoryResult } from "./audit/types";

function getSeverityEmoji(severity: string): string {
  if (severity === "high") return "[!]";
  if (severity === "med") return "[~]";
  return "[-]";
}

function getScoreGrade(score: number): string {
  if (score >= 90) return "A";
  if (score >= 80) return "B";
  if (score >= 70) return "C";
  if (score >= 60) return "D";
  return "F";
}

export function generateMarkdown(result: AuditResult): string {
  const lines: string[] = [];

  lines.push("# Docs AI Discoverability Audit Report");
  lines.push("");
  lines.push(`**URL:** ${result.rootUrl}`);
  lines.push(`**Date:** ${new Date().toISOString().split("T")[0]}`);
  lines.push(`**Overall Score:** ${result.score}/100 (Grade: ${getScoreGrade(result.score)})`);
  lines.push("");
  lines.push("---");
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Pages Crawled | ${result.crawledPages} |`);
  lines.push(`| Chunks Created | ${result.meta.chunkCount} |`);
  lines.push(`| Duration | ${(result.meta.durationMs / 1000).toFixed(1)}s |`);
  lines.push(`| Errors | ${result.meta.errorCount} |`);
  if (result.meta.jsRenderedWarning) {
    lines.push(`| Warning | JS-rendered docs detected |`);
  }
  lines.push("");

  lines.push("## Category Scores");
  lines.push("");
  lines.push("| Category | Score | Max |");
  lines.push("|----------|-------|-----|");
  for (const cat of result.categories) {
    const pct = Math.round((cat.score / cat.max) * 100);
    lines.push(`| ${cat.name} | ${cat.score} | ${cat.max} (${pct}%) |`);
  }
  lines.push("");

  if (result.topFindings.length > 0) {
    lines.push("## Top Issues to Fix");
    lines.push("");
    for (const finding of result.topFindings) {
      lines.push(`### ${getSeverityEmoji(finding.severity)} ${finding.message}`);
      lines.push("");
      if (finding.urls.length > 0) {
        lines.push("Affected URLs:");
        for (const url of finding.urls.slice(0, 5)) {
          lines.push(`- ${url}`);
        }
        if (finding.urls.length > 5) {
          lines.push(`- ... and ${finding.urls.length - 5} more`);
        }
        lines.push("");
      }
    }
  }

  lines.push("## Detailed Category Analysis");
  lines.push("");

  for (const cat of result.categories) {
    lines.push(`### ${cat.name}`);
    lines.push(`**Score:** ${cat.score}/${cat.max}`);
    lines.push("");

    if (cat.findings.length === 0) {
      lines.push("No issues found in this category.");
    } else {
      for (const finding of cat.findings) {
        lines.push(`- ${getSeverityEmoji(finding.severity)} **${finding.severity.toUpperCase()}**: ${finding.message}`);
        if (finding.urls.length > 0) {
          for (const url of finding.urls.slice(0, 3)) {
            lines.push(`  - ${url}`);
          }
          if (finding.urls.length > 3) {
            lines.push(`  - ... and ${finding.urls.length - 3} more`);
          }
        }
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by DAIDS - Docs AI Discoverability Scorer*");

  return lines.join("\n");
}
