import type { AuditResult, Finding, CategoryResult } from "./audit/types";
import PDFDocument from "pdfkit";

function getSeverityEmoji(severity: string): string {
  if (severity === "high") return "[!]";
  if (severity === "med") return "[~]";
  return "[-]";
}

function getScoreGrade(score: number): string {
  if (score >= 90) return "A";
  if (score >= 80) return "B";
  if (score >= 70) return "C";
  if (score >= 60) return "D";
  return "F";
}

export function generateMarkdown(result: AuditResult): string {
  const lines: string[] = [];

  lines.push("# Docs AI Discoverability Audit Report");
  lines.push("");
  lines.push(`**URL:** ${result.rootUrl}`);
  lines.push(`**Date:** ${new Date().toISOString().split("T")[0]}`);
  lines.push(`**Overall Score:** ${result.score}/100 (Grade: ${getScoreGrade(result.score)})`);
  lines.push("");
  lines.push("---");
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Pages Crawled | ${result.crawledPages} |`);
  lines.push(`| Chunks Created | ${result.meta.chunkCount} |`);
  lines.push(`| Duration | ${(result.meta.durationMs / 1000).toFixed(1)}s |`);
  lines.push(`| Errors | ${result.meta.errorCount} |`);
  if (result.meta.jsRenderedWarning) {
    lines.push(`| Warning | JS-rendered docs detected |`);
  }
  lines.push("");

  lines.push("## Category Scores");
  lines.push("");
  lines.push("| Category | Score | Max |");
  lines.push("|----------|-------|-----|");
  for (const cat of result.categories) {
    const pct = Math.round((cat.score / cat.max) * 100);
    lines.push(`| ${cat.name} | ${cat.score} | ${cat.max} (${pct}%) |`);
  }
  lines.push("");

  if (result.topFindings.length > 0) {
    lines.push("## Top Issues to Fix");
    lines.push("");
    for (const finding of result.topFindings) {
      lines.push(`### ${getSeverityEmoji(finding.severity)} ${finding.message}`);
      lines.push("");
      if (finding.urls.length > 0) {
        lines.push("Affected URLs:");
        for (const url of finding.urls.slice(0, 5)) {
          lines.push(`- ${url}`);
        }
        if (finding.urls.length > 5) {
          lines.push(`- ... and ${finding.urls.length - 5} more`);
        }
        lines.push("");
      }
    }
  }

  lines.push("## Detailed Category Analysis");
  lines.push("");

  for (const cat of result.categories) {
    lines.push(`### ${cat.name}`);
    lines.push(`**Score:** ${cat.score}/${cat.max}`);
    lines.push("");

    if (cat.findings.length === 0) {
      lines.push("No issues found in this category.");
    } else {
      for (const finding of cat.findings) {
        lines.push(`- ${getSeverityEmoji(finding.severity)} **${finding.severity.toUpperCase()}**: ${finding.message}`);
        if (finding.urls.length > 0) {
          for (const url of finding.urls.slice(0, 3)) {
            lines.push(`  - ${url}`);
          }
          if (finding.urls.length > 3) {
            lines.push(`  - ... and ${finding.urls.length - 3} more`);
          }
        }
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by DAIDS - Docs AI Discoverability Scorer*");

  return lines.join("\n");
}

export function generatePDF(result: AuditResult): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(24).font("Helvetica-Bold").text("Docs AI Discoverability Audit", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(12).font("Helvetica").text(`Report generated: ${new Date().toISOString().split("T")[0]}`, { align: "center" });
    doc.moveDown(1.5);

    doc.fontSize(10).fillColor("#666666");
    doc.text(`URL: ${result.rootUrl}`);
    doc.moveDown(0.5);
    doc.fillColor("#000000");

    doc.rect(50, doc.y, 500, 80).stroke();
    const boxY = doc.y + 10;
    
    const scoreColor = result.score >= 80 ? "#22c55e" : result.score >= 50 ? "#f59e0b" : "#ef4444";
    doc.fontSize(48).fillColor(scoreColor).text(`${result.score}`, 60, boxY, { width: 100, align: "center" });
    doc.fontSize(12).fillColor("#666666").text("/100", 60, boxY + 50, { width: 100, align: "center" });

    doc.fontSize(10).fillColor("#000000");
    doc.text(`Pages Crawled: ${result.crawledPages}`, 180, boxY);
    doc.text(`Chunks Created: ${result.meta.chunkCount}`, 180, boxY + 15);
    doc.text(`Duration: ${(result.meta.durationMs / 1000).toFixed(1)}s`, 180, boxY + 30);
    doc.text(`Errors: ${result.meta.errorCount}`, 180, boxY + 45);
    doc.text(`Grade: ${getScoreGrade(result.score)}`, 180, boxY + 60);

    doc.y = boxY + 100;

    doc.fontSize(16).font("Helvetica-Bold").fillColor("#000000").text("Category Breakdown");
    doc.moveDown(0.5);

    for (const cat of result.categories) {
      const pct = Math.round((cat.score / cat.max) * 100);
      const catColor = pct >= 80 ? "#22c55e" : pct >= 50 ? "#f59e0b" : "#ef4444";
      
      doc.fontSize(11).font("Helvetica-Bold").fillColor("#000000").text(cat.name, { continued: true });
      doc.font("Helvetica").fillColor(catColor).text(`  ${cat.score}/${cat.max} (${pct}%)`);
      
      const barWidth = 200;
      const filledWidth = (pct / 100) * barWidth;
      doc.rect(50, doc.y + 2, barWidth, 8).fillColor("#e5e7eb").fill();
      doc.rect(50, doc.y + 2, filledWidth, 8).fillColor(catColor).fill();
      doc.moveDown(0.8);

      if (cat.findings.length > 0) {
        doc.fontSize(9).fillColor("#666666");
        for (const finding of cat.findings.slice(0, 2)) {
          const sevLabel = finding.severity === "high" ? "[HIGH]" : finding.severity === "med" ? "[MED]" : "[LOW]";
          doc.text(`  ${sevLabel} ${finding.message.substring(0, 80)}${finding.message.length > 80 ? "..." : ""}`);
        }
        if (cat.findings.length > 2) {
          doc.text(`  ... and ${cat.findings.length - 2} more findings`);
        }
        doc.moveDown(0.3);
      }
    }

    if (result.topFindings.length > 0) {
      doc.addPage();
      doc.fontSize(16).font("Helvetica-Bold").fillColor("#000000").text("Priority Issues");
      doc.moveDown(0.5);

      for (const finding of result.topFindings.slice(0, 10)) {
        const sevColor = finding.severity === "high" ? "#ef4444" : finding.severity === "med" ? "#f59e0b" : "#3b82f6";
        const sevLabel = finding.severity.toUpperCase();
        
        doc.fontSize(10).font("Helvetica-Bold").fillColor(sevColor).text(`[${sevLabel}] `, { continued: true });
        doc.font("Helvetica").fillColor("#000000").text(finding.message);
        
        if (finding.urls.length > 0) {
          doc.fontSize(8).fillColor("#666666");
          for (const url of finding.urls.slice(0, 3)) {
            doc.text(`  - ${url}`);
          }
          if (finding.urls.length > 3) {
            doc.text(`  ... and ${finding.urls.length - 3} more URLs`);
          }
        }
        doc.moveDown(0.5);
      }
    }

    doc.fontSize(8).fillColor("#999999");
    doc.text("Generated by DAIDS - Docs AI Discoverability Scorer", 50, doc.page.height - 50, { align: "center" });

    doc.end();
  });
}
